### ISSUE TITLE
Add docker based deployment support

### ISSUE THREAD

**Issue by chadbr** [JustinBeckwith/trebuchet#17]
There are 2 scenarios I'd like to be able to support here:
1) local docker image deployed to appengine

This one is pretty self explanitory

2) deploying a docker image from one google to another google project.

Currently our CI process builds a docker image and deploys to a "dev" google project. When we want to deploy to our production environment, we push the docker images from the "dev" google project to the "production" project.

It would be nice to be able to list the images from one project and deploy them to another.

**Comment by JustinBeckwith** [comment]
Dropping a quick note - I didn't forget this :)  I had to bootstrap the flex emulator project to make it work, so that's coming along nicely:

https://github.com/JustinBeckwith/flem

Next step is to integrate flem into this project.
